### ISSUE TITLE
Create a way to specify custom path in `SwaggerUi`

### ISSUE THREAD

**Issue by myOmikron** [gammelalf/swaggapi#1]
I'd like to have a method on `SwaggerUi`:

```rs
SwaggerUi::with_path("/docs");
```

just as a convenience method, that should use Default on everything but the path

**Comment by gammelalf** [comment]
Wouldn't the syntax
```rust
SwaggerUi {
    path: "/docs",
    ...Default::default()
}
```
by cleaner and more extensible than writing a bunch of `::with_...`?
